### ISSUE TITLE
Install File Missing DB User session_fb_access_token column

### ISSUE THREAD

**Issue by DamienKeitel** [mjimeyg/alternate-login#1]
In includes/functions.php
before $template->assign_vars

```
   // Begin Alternate Login code
    require_once('functions_alternatelogin.php'); // Include the functions for Alternate Login module
    $user->add_lang('mods/info_ucp_alternatelogin');
    if($user->data['session_fb_access_token'])
    {
        $graph_url = "https://graph.facebook.com/me?" . $user->data['session_fb_access_token'];


        $fb_user = json_decode(get_fb_data($graph_url));

        $fb_lang = $fb_user->locale;
    }
```

session_fb_access_token has not been included in latest alternativelogin_mod_install.php commit

**Comment by mjimeyg** [comment]
This database field is added in the install_mod.xml file.

The alternatelogin_mod_install.php file kept adding a field with a default value of null.  This caused the boolean checks on the $user->data['session_fb_access_token'] value to always come up false and skip the required code.

By putting it in the install_mod.xml file I was able to give it a default value of... no entry but not null, essentially: ''.
