### ISSUE TITLE
new version tag

### ISSUE THREAD

**Issue by lcharette** [mjimeyg/alternate-login#10]
FYI, you can create a Tag in the git-repo for the current code version before new commit. It will create a snapshot of the current master branch. You then can give this link as a mirror of the sourceforge download.

I'll take a look at the new version sometime this week.

**Comment by mjimeyg** [comment]
I'll try and give that a shot, but so far I can't see any changes or a link.  I use Mac OSX Source Tree as I am not very adept at the command line interfaces.

**Comment by lcharette** [comment]
I don't know for Source Tree, but for the official GitHub client, you can't do it, you need command line

See: http://git-scm.com/book/en/Git-Basics-Tagging
