### ISSUE TITLE
Facebook sign in is not working properly.

### ISSUE THREAD

**Issue by XaeroDegreaz** [mjimeyg/alternate-login#13]
After setting everything up, when attempting to sign in using a Facebook login, the screen animates to a dim background, and just sits there.

The application has been setup on Facebook, and all information transplanted properly.

I've tested in Chrome, and Firefox with the same effect.

www.dobydigital.com/forum

**Comment by mjimeyg** [comment]
The version on this site is primarily a development MOD, I recommend going to this URL: https://sourceforge.net/projects/alternatelogin/

That is a version which does work.
