### ISSUE TITLE
al_wl_callback causing Undefined index: al_wl_callback

### ISSUE THREAD

**Issue by DamienKeitel** [mjimeyg/alternate-login#2]
al_wl_callback.

Cause: When a user enables Windows Live in Alternate Login Manager.
Undefined index: al_wl_callback error is warned when user does not input data within the fields
of the Windows Live Manager

**Comment by mjimeyg** [comment]
Are you saying it just needs a check for a more elegant warning or a form validation?  Something to make the user realise they NEED to enter a value before submitting?

**Comment by DamienKeitel** [comment]
I forked and updated the install file to add all config rows before the user inputs.
