### ISSUE TITLE
Translation for the facebook Button

### ISSUE THREAD

**Issue by lcharette** [mjimeyg/alternate-login#4]
I'm currently translating your MOD in French for my website. I notice the main Facebook Connect Button is localized in English. I'm looking for an alternative. The best way would be to use the official button (http://developers.facebook.com/docs/reference/plugins/login/) but I can't get it to work. What would you suggest?

N.B.: I haven't checked the other button yet.

**Comment by mjimeyg** [comment]
The current button is a static image from the Facebook site.  I couldn't use plugins for the log in button without using Javascript and at the time I was trying to stick to php, I am looking to change that now.

The Facebook localisation side of things is found in the style file 'overall_header.html':

<div id="fb-root"></div><script src="http://connect.facebook.net/{S_FB_LOCALE}/all.js#appId={AL_FB_APPID}&xfbml=1"></script>  
<script> 
  window.fbAsyncInit = function() {
    FB.init({appId: '{AL_FB_APPID}', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/{S_FB_LOCALE}/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>

Note the code '{S_AL_FB_LOCALE}'.

The mod pulls the users locale and language choice from the Facebook site and applies the same locale to the Facebook code.

The code to determine the locale is in the file 'functions.php' function 'page_header()'.

**Comment by lcharette** [comment]
Thanks for the reply. I'll send a push request for the french language files when I get home. That's better than nothing for now. I'll see if I can find a way to get the plugins to work so the phpBB translation can be used with the Facebook button. 

For translation purpose, I think I'll add an ACP config options to choose the default locale. For now in functions.php the default is set to "en_GB". In my case I need this to be "fr_something".

I need Facebook Connect on my site ASAP. I've been developing with phpBB for more than two years now so I know where I'm going. If I can get stuff to work on my side I'll try to send it back to you guys.

**Comment by lcharette** [comment]
Sent the pull request for the button. Test it out to make sure it work for you before accepting the request, but I think it should. I took the same code as DamienKeitel in his Facebook For PhpBB Light MOD.
