### ISSUE TITLE
Two phpBB users with the same email

### ISSUE THREAD

**Issue by lcharette** [mjimeyg/alternate-login#7]
I already asked DamienKeitel in his Facebook For PhpBB Light MOD topic on phpbb.com, but I want to know what happen if a user wants to connect to the forum for the first time using his Facebook account, but the Facebook email is used by two phpBB users? I haven't tested yet with this MOD.

For normal phpBB setup, that shouldn't be a problem. But in my case it may happen that two phpBB users have the same email adress.

**Comment by mjimeyg** [comment]
In this event the mod will automatically link the accounts.

I found it annoying when sites I was already a member of implemented Facebook login but when you click the button it created a new account.

**Comment by lcharette** [comment]
That's not really what I had in mind. Let's use this example:
- phpBB user "Pitawawa" has email "malou@domain.com"
- phpBB user "Malou" has email "malou@domain.com"
- Facebook profile "lcharette" has email "malou@domain.com"

They are all my accounts. But for many reasons, on phpBB I'm currently using "Malou" as my main account. When I use facebook Login for the first time, which of the two phpBB account will be linked to my Facebook account? 

I tried on my dummy setup and looks like it's the first user (un user_id order) that's going to be linked to my FB account (In this case "Pitawawa"). But I actually use "Malou", so I have a problem now. 

I guess if I login manually on my "Malou" account and link my FB account in the UCP, the old link will be destroyed? If  so, I'll leave it like that, as a small percentage of users will be affected and it's still a "clean" solution. Otherwise, a "Unlink account" button will be necessary for me, as in issue #8.

**Comment by lcharette** [comment]
Ok, I tried on my test phpBB install. If I'm currently logged in as "Malou" and hit "Connect with Facebook" in the User Control Pannel (which I forgot to change for the translation), I'll be logged out of "Malou" and logged back in as "Pitawawa". No way to change which of my two accounts is linked to Facebook.

**Comment by mjimeyg** [comment]
How are you managing to have two user accounts on phpBB using the same email account?  Whenever I do that it says the email account is in use already.  The emails are the unique identifier for users and the id field is a simple indexing feature.

**Comment by lcharette** [comment]
My board is in French, but in ACP there should be a line in the registration settings called "Allow e-mail address re-use".

Then, if a user wants to get a new password, he have to enter his email and username.

**Comment by mjimeyg** [comment]
This is actually the first time I have heard of the option.  It isn't accounted for in the MOD but I would imagine a check to see if the option is enabled and then an option to either link one of the pre-existing accounts or create a new account.

I will have to look into it further.

**Comment by lcharette** [comment]
I'll see if I can do something like I proposed earlier:

> I guess if I login manually on my "Malou" account and link my FB account in the UCP, the old link will be destroyed?

I think it's the best solution in my case for now. For me the Facebook Login integration is to catch new user by creating a one-click solution for registration (Something the quick account is perfect for). I think it's gonna be easier on the code and more clean if there's the switch in the UCP for the small percentage of people that are going to be affected by this.

Also, I think it will be best to go like this if someone create a new FB account but keeps the same phpBB account.
